### PR TITLE
make open controlled

### PR DESCRIPTION
**Pull request by luke93h**
use props.open when typeof props.open equals boolean

### CODE REVIEW

**Comment by zombieJ** [comment]
Could you help to add the test case?

**Comment by luke93h** [comment]
en,I'll write test case later

**Comment by luke93h** [comment]
hey，I've just added some test case.Sorry for the delay

**Comment by luke93h** [comment]
requestAnimationFrame polyfill comes from https://gist.github.com/paulirish/1579671

**Comment by zombieJ** [comment]
We have dep of `raf`, could you reuse it?

**Comment by luke93h** [comment]
> We have dep of `raf`, could you reuse it?

Do i need to install a new dep ? could you tell your raf address?

**Pull request merged**
