### PR TITLE
 No eslint errors

### PR DESCRIPTION
**Pull request by chenshuai2144**
- [x] fix all eslint
- [x] prettier all code
- [x] Accessibility

### CODE REVIEW

**Comment by chenshuai2144** [comment]
cc @zombieJ

**Comment by zombieJ** [comment]
Seems add `aria-controls` attr. Let's add a patch version for this.

**Comment by afc163** [comment]
image


为啥我本地跑不了 prettier

**Comment by chenshuai2144** [comment]
rc-tools 升级一下版本

**Comment by afc163** [comment]
搞定

**Pull request merged**
