### PR TITLE
fix: onClear triggers onDeselect in multiple mode

### PR DESCRIPTION
**Pull request by imoctopus**
fix [#33790](https://github.com/ant-design/ant-design/issues/33790)

### CODE REVIEW

**Review by blockchainGuru1018 — APPROVED** [review]

**Comment by SCWR** [comment]
请问改进展如何

**Comment by tiber-liber** [comment]
no effect. it calls onDeselect again. if u have lots of tags selected, it will be called many times.

**Comment by xrutayisire** [comment]
Hello,

Do you known if this PR can be merged soon?

**Comment by imoctopus** [comment]
done

**Comment by leotian** [comment]
When will this optimization be merged？

**Comment by ncioj10** [comment]
@yoyo837 Hi, it would be very cool if you could quickly take a look on this, since it's preventing a lot of people from updating ant design downstream.

**Pull request merged**
