### PR TITLE
fix: can not open in web component

### PR DESCRIPTION
**Pull request by 4in**
fix for issue: https://github.com/ant-design/ant-design/issues/27250

### CODE REVIEW

**Comment by 4in** [comment]
image

in web component, event.target is not the origin target.

**Comment by yoyo837** [comment]
Could your add some test case for it?

**Comment by 4in** [comment]
> Could your add some test case for it?

[JSDOM 16.2](https://github.com/jsdom/jsdom/releases/tag/16.2.0) includes basic support for custom elements and is available in [Jest 26.5](https://github.com/facebook/jest/releases/tag/v26.5.0) and above. [See](https://stackoverflow.com/questions/57478484/how-to-test-custom-web-component-with-jest#answer-64606792)

But...

> yarn why v1.22.5
> [1/4] 🤔  Why do we have the module "jest"...?
> [2/4] 🚚  Initialising dependency graph...
> [3/4] 🔍  Finding dependency...
> [4/4] 🚡  Calculating file sizes...
> => Found <b>"jest@24.9.0"</b>
> info Reasons this module exists
>    - "father#umi-test" depends on it
>    - Hoisted from "father#umi-test#jest"
> info Disk size without dependencies: "48KB"
> info Disk size with unique dependencies: "300KB"
> info Disk size with transitive dependencies: "48KB"
> info Number of shared dependencies: 230

@yoyo837

**Comment by zombieJ** [comment]
Thx for contribution. Could you help to provide a test case for this?

**Comment by 4in** [comment]
> Thx for contribution. Could you help to provide a test case for this?

Jest's version is too low to support custom elements.

The version of father#umi-test#jest is 24.9.0, but Jest supports it after  26.5.

**Comment by yoyo837** [comment]
Need upstream supports, you can contribute to them about that also.

**Comment by zombieJ** [comment]
@peachscript

**Pull request merged**
