### PR TITLE
update react refs to use callback instead of strings

### PR DESCRIPTION
**Pull request by coderpawz**
As of React v16 using strings to create refs will no longer work. This is is forward looking change to address future compatibility issues as well as fixing existing deprecation warning thrown by react v15.

For consistency, also moved saveRef from Select.jsx to utils.js

For more info on refs, see https://facebook.github.io/react/docs/refs-and-the-dom.html

### CODE REVIEW

**Comment by HipsterZipster** [comment]
This is a vital PR that unblocks devs that are using React 16.

@afc163 can we please get this merged asap?

**Comment by yesmeck** [comment]
Hello @coderpawz, could you rebase master, then i will merge this.

**Comment by coderpawz** [comment]
hi @yesmeck, all done, thanks!

**Comment by HipsterZipster** [comment]
@yesmeck @coderpawz It seems this got out of sync with master again after it was rebased last time. Can one of you pls rebase and merge when you have a chance?

**Comment by afc163** [comment]
Need to rebase again..

**Comment by HipsterZipster** [comment]
@coderpawz can you please rebase when you have a chance? Need this in

**Comment by yesmeck** [comment]
https://github.com/react-component/select/commit/1a9e57b487dcde1e4c84e500fd23ae1927c0ebd1

**Pull request closed without merging**
