### PR TITLE
Using sequence id for aria

### PR DESCRIPTION
**Pull request by yociduo**
https://github.com/ant-design/ant-design/issues/13569

### CODE REVIEW

**Comment by zombieJ** [comment]
Thanks for contribution. We may change the logic from sequence id (includes TreeSelect) to add id when component did mount to resolve this. Since sequence id in self config SSR still will meet un-sync issue.

cc @chenshuai2144

**Comment by chenshuai2144** [comment]
https://github.com/react-component/select/pull/365

**Comment by zombieJ** [comment]
Since #365 merged, close this one. Thanks for PR.

**Comment by yociduo** [comment]
Thanks

**Pull request closed without merging**
