### PR TITLE
Fix issue https://github.com/ant-design/ant-design/issues/4992#issuecomment-281542159

### PR DESCRIPTION
**Pull request by Keyves**
Resolve the problem of text input jitter

https://github.com/ant-design/ant-design/issues/4992#issuecomment-281542159

### CODE REVIEW

**Comment by afc163** [comment]
Use `&nbsp;`?

**Comment by Keyves** [comment]
Both are OK, the purpose is just to add a character to expand the tolerance.  Use `&nbsp;` will add a text node, Use spaces is need to concat when re-render. which one you think better? need i re-commit?

**Comment by afc163** [comment]
The current change is ugly.

And you can continue to modify and commit in this PR.

**Comment by benjycui** [comment]
How about a patch version? And then close https://github.com/ant-design/ant-design/issues/4992

**Comment by yesmeck** [comment]
Waiting #166

**Pull request merged**
