### PR TITLE
Allow number value for Option

### PR DESCRIPTION
**Pull request by yesmeck**
#115

will close https://github.com/ant-design/ant-design/issues/2857

### CODE REVIEW

**Comment by yesmeck** [comment]
@yiminghe 有空看看

**Comment by yiminghe** [comment]
这个比较复杂，后面逻辑有不少依赖 value string type

**Comment by yesmeck** [comment]
那我先看看现在的实现

**Comment by soulmachine** [comment]
+1

**Comment by Gervwyk** [comment]
Can we please have this. +1

**Comment by lokewei** [comment]
+1

**Comment by yesmeck** [comment]
@yiminghe 更新了。

CI 里加了一句 `TEST_NUMBER_VALUE=1 npm test` 用来测试所有的 number 值。

**Comment by Gervwyk** [comment]
Will numbers as value props in options for select be added in future? or why was this PR closed?

**Comment by ChinaXing** [comment]
坑

**Comment by javahuang** [comment]
这个问题好像还没解决吧？目前都是通过 toString() 很痛苦，TreeNode 组件的 key 同样有这个问题

**Comment by osamamammar** [comment]
I have the same problem... why this issue is closed? I'm using antd version 4.23.0 
is there any solution ?

**Pull request closed without merging**
