### PR TITLE
fix: remove by `Backspace` on input inside dropdown menu effect remove item event

### LINKED ISSUE #834: Type `Backspace` on `input` inside the custom component `dropdownRender` remove last selected value
<b><u>Version</u></b>
Version: 
<b><u>Date Seen</u></b>
Date the bug was found goes here, including the time, if you are submitting more than one bug.
(_21 Sep, 2022_)

<b><u>Versions</u></b>

- Operating System and version: MacOS 12.6
- Browser and Version: **Brave** based on **Chromium**: 105.0.5195.102
- Lib: rc-select@^14.1.2

<b><u>Bug Description</u></b>
I customized the `dropdownRender` component. Inside this component is the input box to filter value.
When I remove the text on input by backspace. The selected value is removing the last item. I inspected the library `rc-select`, I think the root cause from the event listener listen to any input element inside `Select` component.

<b><u>Steps to Reproduce</u></b>
1. Select multiple values.
2. Type some text on input in the dropdown. 
3. Type `Backspace` to remove text on input. 

<b><u>Actual Behavior</u></b>
The last item on the selected value was removed on Select

<b><u>Expected Behavior</u></b>
Shouldn't affect the selected value.

**_Codesandbox_**: https://codesandbox.io/s/rc-select-multiple-search-inside-dropdown-6ibpj6?file=/App.tsx

### PR DESCRIPTION
**Pull request by caocuong2404**
I have fixed the issue #834

### CODE REVIEW

**Comment by caocuong2404** [comment]
@MadCcc please help me to review it

**Comment by caocuong2404** [comment]
@afc163 Review this PR

**Comment by zombieJ** [comment]
Thanks for contribution. But this is by design to ensure that Select with focused always response for the del operation. Please use `stopPropagation` instead.

**Comment by raDiesle** [comment]
should be documented. iny my case we render a text search inside of custom dropdown popup

**Pull request closed without merging**
