### PR TITLE
prop to render selection

### PR DESCRIPTION
**Pull request by plandem**
#56

### CODE REVIEW

**Comment by plandem** [comment]
here is result:
https://www.dropbox.com/s/o3bbxx0lzqzndpd/Screenshot%202016-02-17%2015.42.03.png?dl=0

it can be used like:
```
			<Select dropdownMatchSelectWidth={false} showSearch={false} defaultValue={DashboardIcon[0]} renderSelection={(value, label)=> <div className={"dashboard-icon i" + value}></div>}>
				{DashboardIcon.map(id => {
					return (
						<Option key={id} value={id}><div className={"dashboard-icon i" + id}></div></Option>
					);
				})}
			</Select>
```

**Comment by yiminghe** [comment]
does `optionLabelProp="children"` satisfy your demand?

**Comment by plandem** [comment]
is it possible to render icon? i just could not do it (no any example for it). wanted result is:
https://www.dropbox.com/s/o3bbxx0lzqzndpd/Screenshot%202016-02-17%2015.42.03.png?dl=0

**Comment by yiminghe** [comment]
```
const iconRender = (icon_id) => (<div className={"dashboard-icon i" + icon_id}></div>);

return (
        <Select
            dropdownMatchSelectWidth={false} 
            showSearch={false}
            defaultValue={DashboardIcon[0]} 
            optionLabelProp="children"
        >
                {DashboardIcon.map(id => {
                    return (
                        <Option key={id} value={id}>{iconRender(id)}</Option>
                    );
                })}
            </Select>
        );
```

**Comment by plandem** [comment]
oh! great! the only problem is - if there is a default value, then it does not render 'children' :( But after selection - everything is ok! So looks like there is a bug with defaultValue and 'children' as propLabel

**Comment by yiminghe** [comment]
``` 
defaultValue={String(DashboardIcon[0])}
```

or

```
<Option key={id} value={id}>
```

**Comment by plandem** [comment]
thanks! string key helps, i already found same issue for 'rc-tree-select', never thought that 'keys' at objects always converted to strings so strict compare is not possible in that case.
```
defaultValue={DashboardIcon[0].toString())}
```

your components are really great and have nice non bloating architecture without mess with all this modern 'jss' and etc. Just wondered why it's not so popular?! :(

**Pull request closed without merging**
